version: "3.9"
services:
  mysql:
    image: mysql
    ports:
    - "3306:3306"
    volumes:
    - /var/lib/mysql:/var/lib/mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "test"
    restart: on-failure

